# Generated by Django 2.2.3 on 2020-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beweb', '0004_auto_20190927_1401'),
        ('beweb', '0004_auto_20190927_0857'),
    ]

    operations = [
    ]
